#!/bin/sh

FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	git init
	git remote add origin ${DRONE_REMOTE_URL}
fi

set -e
set -x

git fetch ${FLAGS} origin +refs/heads/${DRONE_COMMIT_BRANCH}:
git checkout -qf FETCH_HEAD

git fetch --no-tags origin +refs/pull/$DRONE_PULL_REQUEST/head
git rev-parse HEAD
git merge FETCH_HEAD

git rev-parse HEAD
git submodule update --init --recursive
